kaltura/player-sdk-native-android

playerSDK/src/main/java/com/kaltura/playersdk/ima/IMAPlayer.java

added listener update when loaded + will play ad.
added a flag to check wether we are in a pause mode - as oppose to trying to load the ad stream

FEC-2397 #comment enable play pause when playing ads #time 1d

---

playerSDK/src/main/java/com/kaltura/playersdk/KalturaPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java

Fec 2532 #comment fix for certain devices #time 1.5h

---

playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java

Added a missing part of the flavor selector -- PlayerViewController.switchFlavor().

Added a missing part of the flavor selector

---

playerSDK/src/main/java/com/kaltura/playersdk/players/KCCRemotePlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KExoPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KWVCPlayer.java

fixing ads not playing on S4 - hiding main player while ad player is on

fixing ads display (especially on S4)

---

playerSDK/src/main/java/com/kaltura/playersdk/KControlsView.java
playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

update to all freeze save state and release methods to support save or not the last player state
so we can recover player in pause mode
solves BG save / no save scenarios

BG handling with and without save state

---

googlemediaframework/src/main/java/com/google/android/libraries/mediaframework/exoplayerextensions/HlsRendererBuilder.java

Sync Google Media Framework with ExoPlayer HLSRendererBuilder

Fix  no sound on HLS live Stream

---

playerSDK/src/main/java/com/kaltura/playersdk/players/KWVCPlayer.java

on WV content the media played from beginning every time and not from last position
please make sure the code in the seek complete event is ok by you

playing WV content from last position - fixing restart every time bug

---

playerSDK/src/main/java/com/kaltura/playersdk/players/KWVCPlayer.java

But use "/local.wvm" for local files.

Back to using "widevine://" url for playback.

---

playerSDK/src/main/java/com/kaltura/playersdk/KPPlayerConfig.java
playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java

prevent Error messages to be sent to Web Layer and to be displayed in Dialog
to enable the Web Dialog use: config.setWebDialogEnabled(true);

Disable Error Dailogs

---

googlemediaframework/src/main/java/com/google/android/libraries/mediaframework/layeredvideo/SimpleVideoPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/KPPlayerConfig.java
playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java
playerSDK/src/main/java/com/kaltura/playersdk/helpers/KIMAManager.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KIMAAdPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KMediaFormat.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

use Activity instead of context in creation of webview

Fem 615 - HTML select tag does not work for Android WebView

---

playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

in case that app going to  Backgound is done during changeMedia or ChangeCongiuration + ADs configured
player stuck

FEM-624 Fix source is not loaded ok if go to bg in changemedia

---

playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

during changeMedia or ChangeCongiuration or loading
cont...  fix also case without ad  preroll

Fix source is not loaded ok in case that app going to Background 

---

playerSDK/src/main/java/com/kaltura/playersdk/KPPlayerConfig.java

add # so the buildSupportedMediaFormats nativeDRMFormats

---

googlemediaframework/src/main/java/com/google/android/libraries/mediaframework/layeredvideo/SimpleVideoPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/KControlsView.java
playerSDK/src/main/java/com/kaltura/playersdk/KPPlayerConfig.java
playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java
playerSDK/src/main/java/com/kaltura/playersdk/helpers/KIMAManager.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KIMAAdPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java
playerSDK/src/main/java/com/kaltura/playersdk/tracks/KTrackActions.java
playerSDK/src/main/java/com/kaltura/playersdk/tracks/KTracksManager.java

supporting now in :config.addConfig("mediaProxy.preferedFlavorBR","500"); bitrate given given in Kbit

Fem 632 - add suppor for KTracksAction -  switchTrackByBitrate

---

KalturaDemos/LocalAssetsDemo/src/main/java/com/kaltura/localassetsdemo/MainActivity.java

LocalAssetsDemo add support for Android 6 permissions

fixed for android 6 permission

---

playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java
playerSDK/src/main/java/com/kaltura/playersdk/tracks/KTracksManager.java

send web the real tracks list even when tracks listener is set

Add Auto Track again after removing if for the comparator phase

---

playerSDK/src/main/java/com/kaltura/playersdk/interfaces/KCastMediaRemoteControl.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KChromeCastPlayer.java

double  getCurrentVolume();
boolean isMute();
long getDuration();

Add some more CC API

---

KalturaDemos/CCPlayerDemo/src/main/java/com/kaltura/ccplayerdemo/MainActivity.java
playerSDK/src/main/java/com/kaltura/playersdk/PlayerViewController.java
playerSDK/src/main/java/com/kaltura/playersdk/interfaces/KCastMediaRemoteControl.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KChromeCastPlayer.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

add isPlaying method
add null protection

Fem 781 Improove CCPlayerDemo - add ability to configure CC pasue in BG

---

playerSDK/src/main/java/com/kaltura/playersdk/casting/KCastProviderImpl.java
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

changes due to changes in the web

Alwayes Send Play event in CC load

---

KalturaDemos/BasicPlayerDemo/src/main/java/com/kaltura/basicplayerdemo/MainActivity.java
KalturaDemos/BasicPlayerDemo/src/main/res/layout/activity_main.xml
playerSDK/src/main/java/com/kaltura/playersdk/players/KPlayerController.java

Also add support in native replay in BasicPLayerDemo App

Fix - Native replay does not work as expected

---

.travis.yml
playerSDK/src/main/java/com/kaltura/playersdk/helpers/KIMAManager.java

with renderingSettings.setEnablePreloading(true); 
it stopped working in IMA since we get RESUME CONTENT EVENT

adaTag with playlist does not work 

---

playerSDK/src/main/java/com/kaltura/playersdk/BrowserActivity.java

check if BarColor string is empty, before parsing it to color.

---

.travis.yml
KalturaDemos/AdPlayerDemo/build.gradle
KalturaDemos/BasicPlayerDemo/build.gradle
KalturaDemos/BasicPlayerTest/build.gradle
KalturaDemos/CCPlayerDemo/build.gradle
KalturaDemos/ChangeMediaDemo/build.gradle
KalturaDemos/DTGPlayerDemo/build.gradle
KalturaDemos/MultiPlayerDemo/build.gradle
KalturaDemos/MultipleDTGPlayerDemo/build.gradle
KalturaDemos/PlayerFragmentDemo/build.gradle
KalturaDemos/inlineplayerdemo/build.gradle
googlemediaframework/build.gradle
kalturaCommon.gradle
kalturaPlay/build.gradle
playerSDK/build.gradle

upgrade all 3rd Party libs as well
move to IMA 3.4.0

upgrade to compile SDK 25

---

playerSDK/src/main/java/com/kaltura/playersdk/KPPlayerConfig.java

Prevent java.io.NotSerializableException: com.kaltura.playersdk.KPPlayerConfig$CacheConfig

Fix FEM-884 & FEM-912

---

playerSDK/src/main/java/com/kaltura/playersdk/casting/KCastProviderV3Impl.java

TPE-18 remove listeners before recreation of KChreomCastPLayer
